# Generated by Django 2.2 on 2019-09-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('para2', models.CharField(max_length=1000)),
                ('para1', models.CharField(max_length=1000)),
            ],
        ),
    ]
